name: Compile Sketch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          
      - name: Install Roger Clark STM32 Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls http://dan.drown.org/stm32duino/package_STM32duino_index.json
          arduino-cli core update-index
          arduino-cli core install stm32duino:STM32F1
          
      - name: Install USBComposite Library
        run: |
          # Membuat folder library
          mkdir -p $HOME/Arduino/libraries
          # Mengunduh library dalam format ZIP (lebih stabil daripada git clone)
          curl -L https://github.com/arpruss/USBComposite_stm32/archive/refs/heads/master.zip -o usbcomposite.zip
          unzip usbcomposite.zip -d $HOME/Arduino/libraries/
          # Mengubah nama folder agar sesuai dengan yang dicari compiler
          mv $HOME/Arduino/libraries/USBComposite_stm32-master $HOME/Arduino/libraries/USBComposite
          
      - name: Prepare and Compile
        run: |
          mkdir -p MySynth
          cp Main.ino MySynth/MySynth.ino
          # Proses kompilasi
          arduino-cli compile --fqbn stm32duino:STM32F1:genericSTM32F103C:device_variant=STM32F103C8 --output-dir ./build ./MySynth
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: firmware-stm32
          path: ./build/*.bin
