name: Compile Sketch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          
      - name: Install STM32 Core (LibMaple)
        run: |
          arduino-cli config init
          # Menggunakan core Roger Clark yang mendukung USBComposite
          arduino-cli config add board_manager.additional_urls https://github.com/rogerclarkmelbourne/Arduino_STM32/raw/master/package_index.json
          arduino-cli core update-index
          arduino-cli core install STM32:stm32
          
      - name: Install USBComposite Library Manually
        run: |
          # Membuat folder library dan mengunduh USBComposite langsung dari GitHub
          mkdir -p $HOME/Arduino/libraries
          git clone https://github.com/arpruss/USBComposite_stm32.git $HOME/Arduino/libraries/USBComposite
          
      - name: Compile
        run: |
          # Kompilasi menggunakan FQBN untuk BluePill (Generic STM32F103C series)
          arduino-cli compile --fqbn STM32:stm32:genericSTM32F103C:device_variant=STM32F103C8,upload_method=serial,type=BASIC,opt=osstd ./Main.cpp --output-dir ./build
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: firmware-stm32
          path: ./build/*.bin
