name: Compile Sketch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          
      - name: Install Roger Clark STM32 Core
        run: |
          arduino-cli config init
          # Menggunakan link resmi untuk core Roger Clark agar tidak 404
          arduino-cli config add board_manager.additional_urls http://dan.drown.org/stm32duino/package_STM32duino_index.json
          arduino-cli core update-index
          # Menginstal core STM32F1 (Roger Clark)
          arduino-cli core install stm32duino:STM32F1
          
      - name: Install USBComposite Library
        run: |
          # Mengunduh library USBComposite langsung dari GitHub
          mkdir -p $HOME/Arduino/libraries
          git clone https://github.com/arpruss/USBComposite_stm32.git $HOME/Arduino/libraries/USBComposite
          
      - name: Prepare and Compile
        run: |
          mkdir -p MySynth
          cp Main.ino MySynth/MySynth.ino
          
          # Menggunakan FQBN Roger Clark: stm32duino:STM32F1:genericSTM32F103C
          arduino-cli compile --fqbn stm32duino:STM32F1:genericSTM32F103C:device_variant=STM32F103C8 --output-dir ./build ./MySynth
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: firmware-stm32
          path: ./build/*.bin
