name: Compile Sketch
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
          
      - name: Install Official STM32 Core
        run: |
          arduino-cli config init
          arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json
          arduino-cli core update-index
          arduino-cli core install STMicroelectronics:stm32
          
      - name: Prepare and Compile
        run: |
          # Trik: Membuat folder khusus agar tidak bentrok dengan nama repository
          mkdir -p MySynth
          cp Main.ino MySynth/MySynth.ino
          
          # Kompilasi dari folder MySynth
          arduino-cli compile --fqbn STMicroelectronics:stm32:GenF1:pnum=BLUEPILL_F103C8,usb=midi --output-dir ./build ./MySynth
          
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: firmware-stm32
          path: ./build/*.bin
